#' @keywords internal
"_PACKAGE"

#' @import methods
NULL

## usethis namespace: start
#' @importFrom data.table :=
#' @importFrom data.table .BY
#' @importFrom data.table .EACHI
#' @importFrom data.table .GRP
#' @importFrom data.table .I
#' @importFrom data.table .N
#' @importFrom data.table .NGRP
#' @importFrom data.table .SD
#' @importFrom data.table data.table
#' @importFrom data.table fread
#' @importFrom data.table melt
#' @importFrom data.table rbindlist
#' @importFrom data.table set
#' @importFrom data.table setDT
#' @importFrom data.table setkey
#' @importFrom data.table setnames
#' @importFrom dplyr filter
#' @importFrom dplyr group_by
#' @importFrom dplyr pull
#' @importFrom dplyr summarize
#' @importFrom fs dir_ls
#' @importFrom fs file_delete
#' @importFrom fs file_info
#' @importFrom future.apply future_lapply
#' @importFrom ggplot2 aes
#' @importFrom ggplot2 coord_sf
#' @importFrom ggplot2 element_text
#' @importFrom ggplot2 geom_abline
#' @importFrom ggplot2 geom_area
#' @importFrom ggplot2 geom_boxplot
#' @importFrom ggplot2 geom_hline
#' @importFrom ggplot2 geom_jitter
#' @importFrom ggplot2 geom_line
#' @importFrom ggplot2 geom_point
#' @importFrom ggplot2 geom_rect
#' @importFrom ggplot2 geom_segment
#' @importFrom ggplot2 geom_sf
#' @importFrom ggplot2 geom_vline
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 ggsave
#' @importFrom ggplot2 ggtitle
#' @importFrom ggplot2 labs
#' @importFrom ggplot2 position_jitter
#' @importFrom ggplot2 scale_colour_manual
#' @importFrom ggplot2 scale_x_continuous
#' @importFrom ggplot2 scale_x_log10
#' @importFrom ggplot2 scale_y_continuous
#' @importFrom ggplot2 theme
#' @importFrom ggplot2 theme_bw
#' @importFrom ggplot2 xlab
#' @importFrom ggplot2 ylab
#' @importFrom graphics abline
#' @importFrom graphics axis
#' @importFrom graphics barplot
#' @importFrom graphics boxplot
#' @importFrom graphics hist
#' @importFrom graphics points
#' @importFrom grDevices dev.off
#' @importFrom grDevices png
#' @importFrom map .rasterToMemory
#' @importFrom map areaAndPolyValue
#' @importFrom map fasterize2
#' @importFrom map rasterToMatch
#' @importFrom pemisc createPrjFile
#' @importFrom pemisc factorValues2
#' @importFrom purrr pluck
#' @importFrom purrr transpose
#' @importFrom rasterVis levelplot
#' @importFrom rasterVis PuOrTheme
#' @importFrom reproducible asPath
#' @importFrom reproducible Cache
#' @importFrom reproducible checkPath
#' @importFrom reproducible fixErrors
#' @importFrom reproducible postProcess
#' @importFrom reproducible prepInputs
#' @importFrom scales hue_pal
#' @importFrom sf st_as_sf
#' @importFrom sf st_join
#' @importFrom sf st_transform
#' @importFrom SpaDES.tools randomPolygon
#' @importFrom SpaDES.tools spread
#' @importFrom SpaDES.tools spread2
#' @importFrom stats na.omit
#' @importFrom stats quantile
#' @importFrom terra classify
#' @importFrom terra compareGeom
#' @importFrom terra crop
#' @importFrom terra crs
#' @importFrom terra crs<-
#' @importFrom terra extend
#' @importFrom terra levels
#' @importFrom terra NAflag<-
#' @importFrom terra ncell
#' @importFrom terra rast
#' @importFrom terra res
#' @importFrom terra setValues
#' @importFrom terra values
#' @importFrom terra writeRaster
#' @importFrom tibble tribble
#' @importFrom tools file_path_sans_ext
#' @importFrom tools toTitleCase
#' @importFrom utils globalVariables
#' @importFrom utils tail
#' @importFrom utils write.csv
#' @importFrom utils write.table
#' @importFrom withr with_seed
## usethis namespace: end
NULL
